### ISSUE TITLE
Error in the CNN-LSTM_model file

### ISSUE THREAD

**Issue by Plahmy** [duncanwp/ClimateBench#6]
I work with your model for a college project and while testing the code I got the
error below. I ran the code in Google colab and everything before worked without problems.
![image](https://user-images.githubusercontent.com/97304051/158365152-0179b3e3-94c5-419f-b108-95c50a91dd4b.png)

**Comment by duncanwp** [comment]
Hi! I think that's because you've converted the prediction `DataArray` to a `Dataset` which doesn't have the `pcolormesh` method. 

You should be able to do:

```m_pred.sel(time=yr).tas.plot.pcolormesh(...)```

**Comment by Plahmy** [comment]
Thanks for your fast answer. Changing this worked for me.
I just double checked and the conversion to a dataset seems to be in your code too.
